fix : gitleak check added

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,3 +39,18 @@ jobs:
           exit-code: '1'
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH'
+
+      - name: Publish Trivy Scan Results to UI
+        if: always() # Ensure this step runs even if the previous ones fail
+        run: |
+          echo "### 🚀 Trivy Scan Results - Backend Image" >> $GITHUB_STEP_SUMMARY
+          echo "#### Image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          trivy image --format table --severity CRITICAL,HIGH docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest || true
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          echo "### 🚀 Trivy Scan Results - Frontend Image" >> $GITHUB_STEP_SUMMARY
+          echo "#### Image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          trivy image --format table --severity CRITICAL,HIGH docker.io/${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest || true
+          echo '```' >> $GITHUB_STEP_SUMMARY
